# Generated by Django 4.0.3 on 2022-03-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('benefits', '0001_initial'),
        ('ratings', '0001_initial'),
        ('locations', '0001_initial'),
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='benefit',
            field=models.ManyToManyField(to='benefits.benefit', verbose_name='Recursos'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='comment',
            field=models.ManyToManyField(to='comments.comment', verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='attractions'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rating',
            field=models.ManyToManyField(to='ratings.rating', verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='descrption',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
