# Generated by Django 4.0.3 on 2022-03-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attraction_benefit_attraction_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['name'], 'verbose_name': 'Atração', 'verbose_name_plural': 'Atrações'},
        ),
        migrations.RenameField(
            model_name='attraction',
            old_name='descrption',
            new_name='description',
        ),
    ]
