# Generated by Django 4.0.3 on 2022-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=150, verbose_name='Endereço')),
                ('line2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('latitude', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.IntegerField(blank=True, null=True, verbose_name='Longitude')),
            ],
        ),
    ]
