# Generated by Django 4.0.3 on 2022-03-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
    ]
