# Generated by Django 4.0.3 on 2022-03-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['name'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
